global:
  slack_api_url: "https://hooks.slack.com/services/SlackWebhookAPI"

route:
  group_by: ["instance", "severity"]
  group_wait: 2m
  group_interval: 5m
  repeat_interval: 5h
  routes:
    - match:
        alertname: InstanceDown
  receiver: 'alert-team'

  receivers:
  - name: 'alert-team'
    slack_configs:
      - channel: "#webhook-test"
        text: "summary: {{ .CommanAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"