---
# tasks file for alert_manager
- name: create alertmanager user group
  group: name="{{groupId}}"
  become: true

- name: create alertmanager user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: /sbin/nologin
    comment: "{{userId}} nologin user"
    createhome: "no"
    state: present

- name: download alertmanager
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: copy alertmanager executable to bin
  copy:
    src: /tmp/alertmanager-{{ version }}.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager/
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: delete alertmanager tmp folder
  file:
    path: /tmp/alertmanager-{{ version }}.linux-amd64/
    state: absent

- name: creates data directory
  file:
    path: /data/alertmanager/
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: creates config directory
  file:
    path: /etc/alertmanager/
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: copy config file
  copy:
    src: "../files/alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml

- name: copy systemd init file
  template:
    src: "../templates/init.service.j2"
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: enable & start alertmanager service
  service:
    name: alertmanager
    enabled: true
    state: started

- name: check if alertmanager is accessible
  uri:
    url: http://localhost:9093
    method: GET
    status_code: 200